require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.3
  Exclude:
    - 'gemfiles/vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 18.36

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 18
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*'

Rails/ApplicationRecord:
  Exclude:
    - 'test/**/*'

Rails/RakeEnvironment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - 'test/**/*'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false
