require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/bundle/**/*'

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/AbcSize:
  Max: 18.36

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 18
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*'

Rails/ApplicationRecord:
  Exclude:
    - 'test/**/*'

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - 'test/**/*'

Style/IfUnlessModifier:
  Enabled: false
