AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Max: 21.86

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*'

Rails:
  Enabled: true

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundOperators:
  AllowForAlignment: true
