os: linux
dist: bionic
language: ruby

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head

addons:
  chrome: stable

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_edge.gemfile

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - nvm install 12
  - node -v
  - npm i -g yarn@^1.21.1
  - yarn
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

jobs:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5.2.gemfile
  fast_finish: true

script: bundle exec rake test:all
