language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_edge.gemfile
  fast_finish: true
